### ISSUE TITLE
I run the profile-model but it returns the fault as follow

### ISSUE THREAD

**Issue by MarkOUzx** [Atcold/torch-Video-Tutorials#3]
```
Building models/3conv.lua model 

/home/usr/torch/install/bin/luajit: bad argument #1 to '?' (expecting number or torch.FloatTensor or torch.FloatStorage at /home/usr/torch/pkg/torch/generic/Tensor.c:1153)
stack traceback:
	[C]: at 0x7f95e89c44d0
	[C]: in function 'FloatTensor'
	profile-model.lua:73: in main chunk
	[C]: in function 'dofile'
	.../usr/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

**Comment by Atcold** [comment]
Where is this file?

**Comment by scarletiin** [comment]
I've just encountered with the same problem, i guess its because of torch new version , but i don't have any idea. 
as mentioned in tutorial 3.0 i tried to run 3conv.lua with torch7-profiling but i got the following  error :
$th profile-model.lua --model models/3conv.lua --res 1*3*256*256 --MACs
Building models/3conv.lua model 
	
/home/fathi/torch/install/bin/luajit: /home/fathi/torch/install/share/lua/5.1/trepl/init.lua:389: module 'models/3conv.lua' not found:No LuaRocks module found for models/3conv.lua
	no field package.preload['models/3conv.lua']
	no file '/home/fathi/.luarocks/share/lua/5.1/models/3conv/lua.lua'
	no file '/home/fathi/.luarocks/share/lua/5.1/models/3conv/lua/init.lua'
	no file '/home/fathi/torch/install/share/lua/5.1/models/3conv/lua.lua'
	no file '/home/fathi/torch/install/share/lua/5.1/models/3conv/lua/init.lua'
	no file './models/3conv/lua.lua'
	no file '/home/fathi/torch/install/share/luajit-2.1.0-beta1/models/3conv/lua.lua'
	no file '/usr/local/share/lua/5.1/models/3conv/lua.lua'
	no file '/usr/local/share/lua/5.1/models/3conv/lua/init.lua'
	no file '/home/fathi/.luarocks/lib/lua/5.1/models/3conv/lua.so'
	no file '/home/fathi/torch/install/lib/lua/5.1/models/3conv/lua.so'
	no file '/home/fathi/torch/install/lib/models/3conv/lua.so'
	no file './models/3conv/lua.so'
	no file '/usr/local/lib/lua/5.1/models/3conv/lua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/fathi/.luarocks/lib/lua/5.1/models/3conv.so'
	no file '/home/fathi/torch/install/lib/lua/5.1/models/3conv.so'
	no file '/home/fathi/torch/install/lib/models/3conv.so'
	no file './models/3conv.so'
	no file '/usr/local/lib/lua/5.1/models/3conv.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/fathi/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	profile-model.lua:36: in main chunk
	[C]: in function 'dofile'
	...athi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

-------------------------------------------------------------------------------------------------------------
i searched around but there was no specific solution , i renamed the model but nothing changed

**Comment by scarletiin** [comment]
mine solved with this :
i have checked You're code in the profile-model.lua , i saw there was require(opt.name) in line 36 , so i just moved the code to the same dir as profile-model.lua and it worked:)
otherwise require would check for torch libraries
@MarkOUzx  putting '*' between dimensions, after --res command might have caused this error
you should put sth like that :--res 1x3x231x231
